#pragma once

#include "../Common/PlatformCom.h"

namespace XusoryEngine::Platform
{
	enum CONSOLE_TEXT_COLOR
	{
		COLOR_RED = FOREGROUND_RED,
		COLOR_GREEN = FOREGROUND_GREEN,
		COLOR_BLUE = FOREGROUND_BLUE,
		COLOR_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN,
		COLOR_PURPLE = FOREGROUND_RED | FOREGROUND_BLUE,
		COLOR_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
		COLOR_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
		COLOR_RED_INTENSITY = COLOR_RED | FOREGROUND_INTENSITY,
		COLOR_GREEN_INTENSITY = COLOR_GREEN | FOREGROUND_INTENSITY,
		COLOR_BLUE_INTENSITY = COLOR_BLUE | FOREGROUND_INTENSITY,
		COLOR_YELLOW_INTENSITY = COLOR_YELLOW | FOREGROUND_INTENSITY,
		COLOR_PURPLE_INTENSITY = COLOR_PURPLE | FOREGROUND_INTENSITY,
		COLOR_CYAN_INTENSITY = COLOR_CYAN | FOREGROUND_INTENSITY,
		COLOR_WHITE_INTENSITY = COLOR_WHITE | FOREGROUND_INTENSITY
	};
}
