#pragma once

#include "DirectX/Common/d3dx12.h"
#include "DirectX/Common/DxDefine.h"
#include "DirectX/Common/DxInclude.h"
#include "DirectX/Common/DxObject.h"

#include "DirectX/DX12/Buffer/Dx12Buffer.h"
#include "DirectX/DX12/Buffer/Dx12Buffer1D.h"
#include "DirectX/DX12/Buffer/Dx12Buffer2D.h"
#include "DirectX/DX12/Buffer/Dx12ConstantBuffer.h"
#include "DirectX/DX12/Buffer/Dx12DepthStencilBuffer.h"
#include "DirectX/DX12/Buffer/Dx12MeshBuffer.h"
#include "DirectX/DX12/Buffer/Dx12RenderTargetBuffer.h"
#include "DirectX/DX12/Buffer/Dx12ShaderResourceBuffer.h"
#include "DirectX/DX12/Buffer/Dx12TextureBuffer.h"
#include "DirectX/DX12/Buffer/Dx12UnorderedAccessBuffer.h"
#include "DirectX/DX12/Buffer/Dx12UploadBuffer.h"

#include "DirectX/DX12/Dx12CommandAllocator.h"
#include "DirectX/Dx12/Dx12CommandList.h"
#include "DirectX/Dx12/Dx12CommandQueue.h"
#include "DirectX/Dx12/Dx12DescriptorAllocator.h"
#include "DirectX/Dx12/Dx12DescriptorHeap.h"
#include "DirectX/Dx12/Dx12Device.h"
#include "DirectX/Dx12/Dx12Fence.h"
#include "DirectX/Dx12/Dx12PipelineState.h"
#include "DirectX/DX12/Dx12RootSignature.h"

#include "DirectX/DxFactory.h"
#include "DirectX/DxShaderCompiler.h"
#include "DirectX/DxSwapChain.h"
#include "DirectX/DxTextureLoader.h"
