#pragma once

#include "../../Common/PlatformDefine.h"

namespace XusoryEngine
{
	constexpr INT DEFAULT_WIN_POS = CW_USEDEFAULT;
	constexpr INT DEFAULT_WIN_SIZE = CW_USEDEFAULT;

	enum SysCursorId : INT
	{
		SYS_CURSOR_ARROW = 32512,
		SYS_CURSOR_TEXT_SELECT = 32513,
		SYS_CURSOR_WAIT = 32514,
		SYS_CURSOR_CROSS = 32515,
		SYS_CURSOR_UP_ARROW = 32516,
		SYS_CURSOR_HANDWRITING = 32631,
		SYS_CURSOR_SIZE_NW_SE = 32642,
		SYS_CURSOR_SIZE_NE_SW = 32643,
		SYS_CURSOR_SIZE_WE = 32644,
		SYS_CURSOR_SIZE_NS = 32645,
		SYS_CURSOR_SIZE_ALL = 32646,
		SYS_CURSOR_NO = 32648,
		SYS_CURSOR_HAND = 32649,
		SYS_CURSOR_APP_STARTING = 32650,
		SYS_CURSOR_APP_HELP = 32651,
		SYS_CURSOR_APP_PIN = 32671,
		SYS_CURSOR_APP_PERSON = 32672
	};

	enum SysIconId : INT
	{
		SYS_ICON_APPLICATION = 32512,
		SYS_ICON_ERROR = 32513,
		SYS_ICON_QUESTION = 32514,
		SYS_ICON_WARNING = 32515,
		SYS_ICON_INFORMATION = 32516,
		SYS_ICON_SHIELD = 32518
	};

	enum MessageBoxStyle
	{
		MSG_BOX_OK = MB_OK,
		MSG_BOX_OK_CANCEL = MB_OKCANCEL,
		MSG_BOX_YES_NO = MB_YESNO,
		MSG_BOX_YES_NO_CANCEL = MB_YESNOCANCEL,
		MSG_BOX_RETRY_CANCEL = MB_RETRYCANCEL,
		MSG_BOX_ABORT_RETRY_IGNORE = MB_ABORTRETRYIGNORE,
		MSG_BOX_CANCEL_TRY_CONTINUE = MB_CANCELTRYCONTINUE,
	};

	enum MessageBoxIcon
	{
		MSG_ICON_STOP = MB_ICONSTOP,
		MSG_ICON_WARNING = MB_ICONWARNING,
		MSG_ICON_QUESTION = MB_ICONQUESTION,
		MSG_ICON_INFORMATION = MB_ICONINFORMATION
	};

	enum MessageBoxCode
	{
		MSG_CODE_NO = IDNO,
		MSG_CODE_OK = IDOK,
		MSG_CODE_YES = IDYES,
		MSG_CODE_ABORT = IDABORT,
		MSG_CODE_RETRY = IDRETRY,
		MSG_CODE_CANCEL = IDCANCEL,
		MSG_CODE_IGNORE = IDIGNORE,
		MSG_CODE_CONTINUE = IDCONTINUE,
		MSG_CODE_TRY_AGAIN = IDTRYAGAIN,
	};
}
